# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0cbc38bfba15b304ca7576bb8be29919015bab2e7ee3ba71b254d0a3bd3d67b5d4125abae02612cb6aa385a9525d42b180a2a23a6298c06859847d9099c7052f

test:
  secret_key_base: fff2d62bcc001a1847ce8f8eb2f12421657da063039d058c4e9a4ef6e2989bdfd042b28da1bfb777070c755a668ee2117a922e1b50d07a0e74684cdf62a89816

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
